kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kubernetes-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30081
    hostPort: 8081
    protocol: TCP
  - containerPort: 30306
    hostPort: 3306
    protocol: TCP